- name: upgrade system
  apt: upgrade=dist update_cache=yes force=yes

- name: install dependencies
  apt: name={{ item }} state=present force=yes
  with_items:
    - man
    - git
    - ntp
    - vim
    - zsh
    - ssh
    - htop
    - tmux
    - sudo
    - curl
    - btrfs-tools
    - openssl
    - unattended-upgrades
    - apt-listchanges
    - corkscrew
    - ca-certificates
    - build-essential
    - nodejs
    - npm
    - golang
    - python-pip
    - dnsutils
    - locales
    - locales-all

- name: Ensure fr_FR locale exists
  locale_gen: name=fr_FR.UTF-8 state=present

- name: set hostname
  hostname: name={{hostname}}
  when: hostname is defined

- name: update hosts file
  lineinfile: >
    dest=/etc/hosts
    regexp='^127\.0\.1\.1'
    line='127.0.1.1 {{ hostname }}'
    owner=root group=root mode=0644
  when: hostname is defined

- name: activate unattended-upgrades
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root

- name: configure root bash
  copy: src=bashrc dest=/root/.bashrc

- name: configure keyboard layout
  copy: src=keyboard dest=/etc/default/keyboard

- name: create developers group
  group: name=developers state=present

- name: create shared directory
  file: path=/var/shared group=developers mode=0775 state=directory

- name: create directory placeholder (need by docker volume)
  file: path=/var/shared/.placeholder state=touch

